name: lab01
on: [push]
jobs:
  test: 
    runs-on: ubuntu-latest
    steps: 
      - run: pip install nbconvert
      - uses: actions/checkout
      - run: python -m nbconvert  lab_01/pint_and_boiling_point.ipynb

