  name: assignment05
  on: [push]
  jobs:
    test: 
      runs-on: ubuntu-latest
      steps: 
        - run: pip install nbconvert ipykernel pint matplotlib scipy open-atmos-jupyter-utils numpy
        - uses: actions/checkout@v2
        - run: sudo apt-get update && sudo apt-get install -y pandoc inkscape texlive-xetex
        - run: python -m nbconvert --to pdf --execute lab_05/assignment05.ipynb
        - uses: actions/upload-artifact@v4
          with: 
            path: lab_05/assignment05.pdf




