name: lab01
on: [push]
jobs:
  test: 
    runs-on: ubuntu-latest
    steps: 
      - run: pip install nbconvert
      - uses: actions/checkout@v2
      - run: sudo apt-get install pandoc inkscape
      - run: python -m nbconvert  lab_01\pint_and_boiling_point.ipynb


